# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import barang_pb2 as barang__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in barang_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BarangServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBarang = channel.unary_unary(
                '/barang.BarangService/CreateBarang',
                request_serializer=barang__pb2.Barang.SerializeToString,
                response_deserializer=barang__pb2.BarangResponse.FromString,
                _registered_method=True)
        self.GetBarang = channel.unary_unary(
                '/barang.BarangService/GetBarang',
                request_serializer=barang__pb2.BarangRequest.SerializeToString,
                response_deserializer=barang__pb2.BarangResponse.FromString,
                _registered_method=True)
        self.UpdateBarang = channel.unary_unary(
                '/barang.BarangService/UpdateBarang',
                request_serializer=barang__pb2.Barang.SerializeToString,
                response_deserializer=barang__pb2.BarangResponse.FromString,
                _registered_method=True)
        self.DeleteBarang = channel.unary_unary(
                '/barang.BarangService/DeleteBarang',
                request_serializer=barang__pb2.BarangRequest.SerializeToString,
                response_deserializer=barang__pb2.BarangResponse.FromString,
                _registered_method=True)


class BarangServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateBarang(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBarang(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBarang(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBarang(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BarangServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBarang': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBarang,
                    request_deserializer=barang__pb2.Barang.FromString,
                    response_serializer=barang__pb2.BarangResponse.SerializeToString,
            ),
            'GetBarang': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBarang,
                    request_deserializer=barang__pb2.BarangRequest.FromString,
                    response_serializer=barang__pb2.BarangResponse.SerializeToString,
            ),
            'UpdateBarang': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBarang,
                    request_deserializer=barang__pb2.Barang.FromString,
                    response_serializer=barang__pb2.BarangResponse.SerializeToString,
            ),
            'DeleteBarang': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBarang,
                    request_deserializer=barang__pb2.BarangRequest.FromString,
                    response_serializer=barang__pb2.BarangResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'barang.BarangService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('barang.BarangService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BarangService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateBarang(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barang.BarangService/CreateBarang',
            barang__pb2.Barang.SerializeToString,
            barang__pb2.BarangResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBarang(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barang.BarangService/GetBarang',
            barang__pb2.BarangRequest.SerializeToString,
            barang__pb2.BarangResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBarang(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barang.BarangService/UpdateBarang',
            barang__pb2.Barang.SerializeToString,
            barang__pb2.BarangResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBarang(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barang.BarangService/DeleteBarang',
            barang__pb2.BarangRequest.SerializeToString,
            barang__pb2.BarangResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
